owner: skynet2982 # GitHub username
repo: toulouse-social-uptime # GitHub repository name
sites: # List of endpoints to track
  - name: Toulouse Social
    url: https://toulouse.social
assignees: # Users to assign downtime issues (optional)
  - skynet2982
status-website:
  cname: status.toulouse.social # Custom domain CNAME
  name: Toulouse Social Status # Status website title
